# Generated by Django 5.0.6 on 2024-05-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='activity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
