# Generated by Django 5.0.6 on 2024-05-13 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usereducation_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='usereducation',
            name='update_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='update_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
