# Generated by Django 5.0.6 on 2024-05-13 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usereducation_update_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereducation',
            name='activity',
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='update_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
