# Generated by Django 5.0.6 on 2024-05-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_books_print_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='print_by',
        ),
        migrations.AddField(
            model_name='books',
            name='print_by',
            field=models.ManyToManyField(null=True, related_name='publishers', to='users.printshop'),
        ),
    ]
