# Generated by Django 5.0.6 on 2024-05-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_books_print_by_books_print_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='print_by',
            field=models.ManyToManyField(related_name='publishers', to='users.printshop'),
        ),
    ]
